# Generated by Django 4.2.11 on 2026-04-15 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0, help_text='Available balance in tiyin')),
                ('held_balance', models.PositiveBigIntegerField(default=0, help_text='Funds held in escrow for active jobs')),
                ('total_earned', models.PositiveBigIntegerField(default=0, help_text='Lifetime earned (workers only)')),
                ('total_spent', models.PositiveBigIntegerField(default=0, help_text='Lifetime spent (employers only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'payments_wallets',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=20)),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('payment_url', models.URLField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'db_table': 'payments_payment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('job_payment', 'Job Payment (Escrow)'), ('job_release', 'Job Release (Worker Payout)'), ('commission', 'Platform Commission'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal')], db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in tiyin', validators=[django.core.validators.MinValueValidator(1)])),
                ('balance_before', models.PositiveBigIntegerField(help_text='Wallet balance before this transaction')),
                ('balance_after', models.PositiveBigIntegerField(help_text='Wallet balance after this transaction')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='completed', max_length=10)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID from external payment provider (Payme, Click)', max_length=200)),
                ('provider', models.CharField(blank=True, help_text='Payment provider name (payme, click, internal)', max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='jobs.job')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'payments_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='payments_tr_wallet__d9ff12_idx'), models.Index(fields=['wallet', 'transaction_type'], name='payments_tr_wallet__2997ed_idx'), models.Index(fields=['job'], name='payments_tr_job_id_168f9e_idx'), models.Index(fields=['external_id'], name='payments_tr_externa_bb71f2_idx')],
            },
        ),
    ]
